test:
	@echo "Running tests with coverage"
	go test -cover ./...

lint: prerequisites
	@echo "Running linter"
	golangci-lint run ./...
	go vet ./...

build:
	@echo "Building binary"
	go build

install:
	go install ./...

run:
	go run main.go

watch:
	air

prerequisites:
	@echo "Installing prerequisites"
	go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.52.2
	go install github.com/cosmtrek/air@latest
